# Generated by Django 5.0.6 on 2024-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='some string', max_length=500),
        ),
    ]
