# Generated by Django 5.0.6 on 2024-05-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_text_blog_name_rename_text_blogpost_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
