# Generated by Django 5.0.6 on 2024-05-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
